/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as RideRequestRouteImport } from './routes/ride-request'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MerchantsRouteImport } from './routes/merchants'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FoodRouteImport } from './routes/food'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as MenuRestaurantSlugRouteImport } from './routes/menu.$restaurantSlug'
import { Route as DashboardShopRouteImport } from './routes/dashboard.shop'
import { Route as DashboardRestaurantRouteImport } from './routes/dashboard.restaurant'
import { Route as DashboardDriverRouteImport } from './routes/dashboard.driver'
import { Route as DashboardCustomerRouteImport } from './routes/dashboard.customer'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as OrdersIdTrackingRouteImport } from './routes/orders.$id.tracking'
import { Route as DashboardRestaurantOrdersRouteImport } from './routes/dashboard.restaurant.orders'
import { Route as DashboardRestaurantMenuRouteImport } from './routes/dashboard.restaurant.menu'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const RideRequestRoute = RideRequestRouteImport.update({
  id: '/ride-request',
  path: '/ride-request',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsRoute = MerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)
const MenuRestaurantSlugRoute = MenuRestaurantSlugRouteImport.update({
  id: '/menu/$restaurantSlug',
  path: '/menu/$restaurantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardShopRoute = DashboardShopRouteImport.update({
  id: '/dashboard/shop',
  path: '/dashboard/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRestaurantRoute = DashboardRestaurantRouteImport.update({
  id: '/dashboard/restaurant',
  path: '/dashboard/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomerRoute = DashboardCustomerRouteImport.update({
  id: '/dashboard/customer',
  path: '/dashboard/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdTrackingRoute = OrdersIdTrackingRouteImport.update({
  id: '/orders/$id/tracking',
  path: '/orders/$id/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRestaurantOrdersRoute =
  DashboardRestaurantOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => DashboardRestaurantRoute,
  } as any)
const DashboardRestaurantMenuRoute = DashboardRestaurantMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRestaurantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/architecture': typeof ArchitectureRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/drivers': typeof DriversRoute
  '/food': typeof FoodRoute
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/ride-request': typeof RideRequestRoute
  '/rides': typeof RidesRoute
  '/shops': typeof ShopsRoute
  '/users': typeof UsersRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/restaurant': typeof DashboardRestaurantRouteWithChildren
  '/dashboard/shop': typeof DashboardShopRoute
  '/menu/$restaurantSlug': typeof MenuRestaurantSlugRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/dashboard/restaurant/menu': typeof DashboardRestaurantMenuRoute
  '/dashboard/restaurant/orders': typeof DashboardRestaurantOrdersRoute
  '/orders/$id/tracking': typeof OrdersIdTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/architecture': typeof ArchitectureRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/drivers': typeof DriversRoute
  '/food': typeof FoodRoute
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/ride-request': typeof RideRequestRoute
  '/rides': typeof RidesRoute
  '/shops': typeof ShopsRoute
  '/users': typeof UsersRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/restaurant': typeof DashboardRestaurantRouteWithChildren
  '/dashboard/shop': typeof DashboardShopRoute
  '/menu/$restaurantSlug': typeof MenuRestaurantSlugRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/dashboard/restaurant/menu': typeof DashboardRestaurantMenuRoute
  '/dashboard/restaurant/orders': typeof DashboardRestaurantOrdersRoute
  '/orders/$id/tracking': typeof OrdersIdTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/architecture': typeof ArchitectureRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/drivers': typeof DriversRoute
  '/food': typeof FoodRoute
  '/login': typeof LoginRoute
  '/merchants': typeof MerchantsRoute
  '/register': typeof RegisterRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/ride-request': typeof RideRequestRoute
  '/rides': typeof RidesRoute
  '/shops': typeof ShopsRoute
  '/users': typeof UsersRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/restaurant': typeof DashboardRestaurantRouteWithChildren
  '/dashboard/shop': typeof DashboardShopRoute
  '/menu/$restaurantSlug': typeof MenuRestaurantSlugRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/dashboard/restaurant/menu': typeof DashboardRestaurantMenuRoute
  '/dashboard/restaurant/orders': typeof DashboardRestaurantOrdersRoute
  '/orders/$id/tracking': typeof OrdersIdTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/architecture'
    | '/cart'
    | '/contact'
    | '/drivers'
    | '/food'
    | '/login'
    | '/merchants'
    | '/register'
    | '/restaurants'
    | '/ride-request'
    | '/rides'
    | '/shops'
    | '/users'
    | '/dashboard/admin'
    | '/dashboard/customer'
    | '/dashboard/driver'
    | '/dashboard/restaurant'
    | '/dashboard/shop'
    | '/menu/$restaurantSlug'
    | '/restaurants/$id'
    | '/dashboard/restaurant/menu'
    | '/dashboard/restaurant/orders'
    | '/orders/$id/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/architecture'
    | '/cart'
    | '/contact'
    | '/drivers'
    | '/food'
    | '/login'
    | '/merchants'
    | '/register'
    | '/restaurants'
    | '/ride-request'
    | '/rides'
    | '/shops'
    | '/users'
    | '/dashboard/admin'
    | '/dashboard/customer'
    | '/dashboard/driver'
    | '/dashboard/restaurant'
    | '/dashboard/shop'
    | '/menu/$restaurantSlug'
    | '/restaurants/$id'
    | '/dashboard/restaurant/menu'
    | '/dashboard/restaurant/orders'
    | '/orders/$id/tracking'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/architecture'
    | '/cart'
    | '/contact'
    | '/drivers'
    | '/food'
    | '/login'
    | '/merchants'
    | '/register'
    | '/restaurants'
    | '/ride-request'
    | '/rides'
    | '/shops'
    | '/users'
    | '/dashboard/admin'
    | '/dashboard/customer'
    | '/dashboard/driver'
    | '/dashboard/restaurant'
    | '/dashboard/shop'
    | '/menu/$restaurantSlug'
    | '/restaurants/$id'
    | '/dashboard/restaurant/menu'
    | '/dashboard/restaurant/orders'
    | '/orders/$id/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  DriversRoute: typeof DriversRoute
  FoodRoute: typeof FoodRoute
  LoginRoute: typeof LoginRoute
  MerchantsRoute: typeof MerchantsRoute
  RegisterRoute: typeof RegisterRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  RideRequestRoute: typeof RideRequestRoute
  RidesRoute: typeof RidesRoute
  ShopsRoute: typeof ShopsRoute
  UsersRoute: typeof UsersRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardCustomerRoute: typeof DashboardCustomerRoute
  DashboardDriverRoute: typeof DashboardDriverRoute
  DashboardRestaurantRoute: typeof DashboardRestaurantRouteWithChildren
  DashboardShopRoute: typeof DashboardShopRoute
  MenuRestaurantSlugRoute: typeof MenuRestaurantSlugRoute
  OrdersIdTrackingRoute: typeof OrdersIdTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ride-request': {
      id: '/ride-request'
      path: '/ride-request'
      fullPath: '/ride-request'
      preLoaderRoute: typeof RideRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants': {
      id: '/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof MerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/menu/$restaurantSlug': {
      id: '/menu/$restaurantSlug'
      path: '/menu/$restaurantSlug'
      fullPath: '/menu/$restaurantSlug'
      preLoaderRoute: typeof MenuRestaurantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/shop': {
      id: '/dashboard/shop'
      path: '/dashboard/shop'
      fullPath: '/dashboard/shop'
      preLoaderRoute: typeof DashboardShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/restaurant': {
      id: '/dashboard/restaurant'
      path: '/dashboard/restaurant'
      fullPath: '/dashboard/restaurant'
      preLoaderRoute: typeof DashboardRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customer': {
      id: '/dashboard/customer'
      path: '/dashboard/customer'
      fullPath: '/dashboard/customer'
      preLoaderRoute: typeof DashboardCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id/tracking': {
      id: '/orders/$id/tracking'
      path: '/orders/$id/tracking'
      fullPath: '/orders/$id/tracking'
      preLoaderRoute: typeof OrdersIdTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/restaurant/orders': {
      id: '/dashboard/restaurant/orders'
      path: '/orders'
      fullPath: '/dashboard/restaurant/orders'
      preLoaderRoute: typeof DashboardRestaurantOrdersRouteImport
      parentRoute: typeof DashboardRestaurantRoute
    }
    '/dashboard/restaurant/menu': {
      id: '/dashboard/restaurant/menu'
      path: '/menu'
      fullPath: '/dashboard/restaurant/menu'
      preLoaderRoute: typeof DashboardRestaurantMenuRouteImport
      parentRoute: typeof DashboardRestaurantRoute
    }
  }
}

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

interface DashboardRestaurantRouteChildren {
  DashboardRestaurantMenuRoute: typeof DashboardRestaurantMenuRoute
  DashboardRestaurantOrdersRoute: typeof DashboardRestaurantOrdersRoute
}

const DashboardRestaurantRouteChildren: DashboardRestaurantRouteChildren = {
  DashboardRestaurantMenuRoute: DashboardRestaurantMenuRoute,
  DashboardRestaurantOrdersRoute: DashboardRestaurantOrdersRoute,
}

const DashboardRestaurantRouteWithChildren =
  DashboardRestaurantRoute._addFileChildren(DashboardRestaurantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchitectureRoute: ArchitectureRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  DriversRoute: DriversRoute,
  FoodRoute: FoodRoute,
  LoginRoute: LoginRoute,
  MerchantsRoute: MerchantsRoute,
  RegisterRoute: RegisterRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  RideRequestRoute: RideRequestRoute,
  RidesRoute: RidesRoute,
  ShopsRoute: ShopsRoute,
  UsersRoute: UsersRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardCustomerRoute: DashboardCustomerRoute,
  DashboardDriverRoute: DashboardDriverRoute,
  DashboardRestaurantRoute: DashboardRestaurantRouteWithChildren,
  DashboardShopRoute: DashboardShopRoute,
  MenuRestaurantSlugRoute: MenuRestaurantSlugRoute,
  OrdersIdTrackingRoute: OrdersIdTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
